[package]
name = "godot-rapier"
version = "0.1.0"
edition = "2021"
rust-version = "1.77.1"
license = "MPL-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
single = []
double = []
enhanced-determinism = ["rapier2d/enhanced-determinism", "rapier2d-f64/enhanced-determinism"]
simd-stable = ["rapier2d/simd-stable", "rapier2d-f64/simd-stable"]
simd-nightly = ["rapier2d/simd-nightly", "rapier2d-f64/simd-nightly"]
# wasm-bindgen = ["rapier2d/wasm-bindgen", "rapier2d-f64/wasm-bindgen"]
parallel = ["rapier2d/parallel", "rapier2d-f64/parallel"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features=["debug-log"] }
rapier2d = {git = "https://github.com/dimforge/rapier", branch = "master", features=["serde-serialize"]}
rapier2d-f64 = {git = "https://github.com/dimforge/rapier", branch = "master", features=["serde-serialize"]}
salva2d = { git = "https://github.com/ughuuu/salva", branch = "update-to-rapier-0.19", features = ["rapier"] }

[patch.crates-io]
rapier2d = {git = "https://github.com/dimforge/rapier", branch = "master"}
rapier2d-f64 = {git = "https://github.com/dimforge/rapier", branch = "master"}
parry2d = {git = "https://github.com/dimforge/parry", branch = "master"}
parry2d-f64 = {git = "https://github.com/dimforge/parry", branch = "master"}

[profile.release]
codegen-units = 1
lto = "fat"

[profile.dev]
split-debuginfo = "unpacked"

[profile.dev.build-override]
opt-level = 3
