[package]
name = "godot-rapier"
version = "0.1.0"
edition = "2021"
rust-version = "1.77.1"
license = "MPL-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }

[profile.dev.package.rapier3d]
opt-level = 3
