[target.wasm32-unknown-emscripten]
rustflags = [
  "-C",
  "link-args=-sSIDE_MODULE=2",
  "-C",
  "link-args=-pthread",                                    # was -sUSE_PTHREADS=1 in earlier emscripten versions
  "-C",
  "target-feature=+atomics,+bulk-memory,+mutable-globals",
  "-Clink-args=-sEXPORT_ALL=1",
  # Trying out stuff
  # "-Clink-arg=-O0",
  # "-Clink-arg=-g",
  # "-Clink-arg=-sASSERTIONS=2",
  # "-Clink-arg=-sDEMANGLE_SUPPORT=1",
  # "-Clink-arg=-sEMULATE_FUNCTION_POINTER_CASTS",
  # ---
  "-Clink-arg=-fwasm-exceptions",
  "-C",
  "link-args=-sSUPPORT_LONGJMP=wasm",
  "-Cllvm-args=-enable-emscripten-cxx-exceptions=0",
  "-Cllvm-args=-wasm-enable-sjlj",
  "-C",
  "link-args=-sDISABLE_EXCEPTION_CATCHING=1",
  "-Zlink-native-libraries=no",
]
[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi23-clang"
[target.aarch64-linux-android]
linker = "aarch64-linux-android23-clang"
[target.x86_64-linux-android]
linker = "x86_64-linux-android23-clang"
[target.i686-linux-android]
linker = "i686-linux-android23-clang"