name: 🤖 Android Builds
on:
  workflow_call:

jobs:
  android:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.arch }} ${{ matrix.precision }} ${{ matrix.features }}
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64-linux-android", "aarch64-linux-android", "i686-linux-android", "armv7-linux-androideabi"]
        precision: [single]
        features: ["simd-stable,parallel", enhanced-determinism]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
          platform: android
          precision: ${{ matrix.precision }}
          features: ${{ matrix.features }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: godot-rapier-2d-${{ matrix.precision }}-${{ matrix.features }}
          path: |
            ${{ github.workspace }}/bin/**
            !${{ github.workspace }}/bin/project.godot
