name: 🤖 Android Builds
on:
  workflow_call:

jobs:
  android:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.dimensions.short }} ${{ matrix.precision }} ${{ matrix.features.name }} ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64-linux-android", "aarch64-linux-android", "i686-linux-android", "armv7-linux-androideabi"]
        precision: [single]
        #dimensions: [{"feature": "dim2", "short": "2d"}, {"feature": "dim3", "short": "3d"}]
        dimensions: [{"feature": "dim2", "short": "2d"}]
        features: [{"feature":"parallel,simd-stable", "name": "normal"}, {"feature":"enhanced-determinism", "name": "enhanced-determinism"}]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
          features: ${{ matrix.features.feature }},${{ matrix.precision }}_${{ matrix.dimensions.feature }}
      - name: Copy to bin
        shell: sh
        run: |
          mv target/release/libgodot_rapier.so bin${{ matrix.dimensions.short }}/addons/godot-rapier${{ matrix.dimensions.short }}/bin/libgodot_rapier.android.so
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: godot-rapier-${{ matrix.dimensions.short }}-${{ matrix.precision }}-${{ matrix.features.name }}
          path: |
            ${{ github.workspace }}/bin${{ matrix.dimensions.short }}/**
            !${{ github.workspace }}/bin${{ matrix.dimensions.short }}/project.godot
          if-no-files-found: error
          overwrite: true
