name: Godot Builds
on:
  workflow_call:

jobs:
  godot:
    runs-on: "ubuntu-latest"
    name: ${{ matrix.dimensions }} ${{ matrix.precision }} ${{ matrix.features }}
    strategy:
      fail-fast: false
      matrix:
        precision: [single] #, double]
        dimensions: ["2d", "3d"]
        features: ["simd-parallel", "enhanced-determinism"]

    steps:
      - uses: actions/checkout@v4
      - name: Update plugin.info.cfg
        shell: sh
        run: |
          sed -i "s/<flavour>/godot-rapier-2d-${{ matrix.precision }}-${{ matrix.features }}/g" bin2d/addons/godot-rapier2d/plugin.info.cfg
          sed -i "s/<flavour>/godot-rapier-3d-${{ matrix.precision }}-${{ matrix.features }}/g" bin3d/addons/godot-rapier3d/plugin.info.cfg
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: godot-rapier-${{ matrix.dimensions }}-${{ matrix.precision }}-${{ matrix.features }}-gdext
          path: |
            bin${{ matrix.dimensions }}
            !bin${{ matrix.dimensions }}/test/*
            !bin${{ matrix.dimensions }}/tests/*
            !bin${{ matrix.dimensions }}/base/*
            !bin${{ matrix.dimensions }}/export_presets.cfg
            !bin${{ matrix.dimensions }}/project.godot
            !bin${{ matrix.dimensions }}/test.gd
            !bin${{ matrix.dimensions }}/start.gd
            !bin${{ matrix.dimensions }}/start.tscn
            !bin${{ matrix.dimensions }}/test.tscn
          if-no-files-found: error
