name: Godot Builds
on:
  workflow_call:

jobs:
  godot:
    runs-on: "ubuntu-latest"
    name: ${{ matrix.dimensions }} ${{ matrix.precision }} ${{ matrix.features }}
    strategy:
      fail-fast: false
      matrix:
        precision: [single]
        dimensions: ["2d", "3d"]
        features: ["simd-parallel", "enhanced-determinism"]

    steps:
      - uses: actions/checkout@v4
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: godot-rapier-${{ matrix.dimensions }}-${{ matrix.precision }}-${{ matrix.features }}-gdext
          path: |
            bin${{ matrix.dimensions }}
            !bin${{ matrix.dimensions }}/test/*
            !bin${{ matrix.dimensions }}/export_presets.cfg
            !bin${{ matrix.dimensions }}/project.godot
            !bin${{ matrix.dimensions }}/test.gd
            !bin${{ matrix.dimensions }}/test.tscn
          if-no-files-found: error
