name: 🍏 iOS Builds
on:
  workflow_call:

jobs:
  ios:
    runs-on: "macos-latest"
    name: ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
    strategy:
      fail-fast: false
      matrix:
        arch: [{arch: "arm64", rust: "aarch64-apple-ios"}]
        precision: [single]
        features: [simd-stable, enhanced-determinism]
        rust_features: ["simd-stable,parallel", enhanced-determinism]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Build ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch.arch }}
          rust_target: ${{ matrix.arch.rust }}
          platform: ios
          precision: ${{ matrix.precision }}
          features: ${{ matrix.rust_features }}

      - name: Sign dylib ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        shell: pwsh
        env:
          APPLE_CERT_BASE64: ${{ secrets.PROD_MACOS_CERTIFICATE }}
          APPLE_CERT_PASSWORD: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
          APPLE_DEV_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
          APPLE_DEV_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
          APPLE_DEV_PASSWORD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
          APPLE_DEV_APP_ID: ${{ secrets.PROD_MACOS_APPLE_DEV_APP_ID }}
        run: |
          ./scripts/ci-sign-macos.ps1 bin/addons/godot-rapier2d/bin/libphysics_server_rapier2d.ios.template_debug.dylib
          ./scripts/ci-sign-macos.ps1 bin/addons/godot-rapier2d/bin/libphysics_server_rapier2d.ios.template_release.dylib
        if: ${{ env.APPLE_DEV_ID }}

      - name: Upload ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/upload
        with:
          precision: ${{ matrix.precision }}
          features: ${{ matrix.features }}
