name: 🍏 iOS Builds
on:
  workflow_call:

jobs:
  ios:
    runs-on: "macos-latest"
    name: ${{ matrix.dimensions }} ${{ matrix.precision }} ${{ matrix.features.name }} ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch: ["aarch64-apple-ios"]
        precision: [single]
        dimensions: [dim2, dim3]
        features: [{"feature":"parallel,simd-stable", "name": "normal"}, {"feature":"enhanced-determinism", "name": "enhanced-determinism"}]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
          features: ${{ matrix.features.feature }},${{ matrix.precision }}_${{ matrix.dimensions }}

      - name: iOS Sign
        shell: pwsh
        env:
          APPLE_CERT_BASE64: ${{ secrets.PROD_MACOS_CERTIFICATE }}
          APPLE_CERT_PASSWORD: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
          APPLE_DEV_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
          APPLE_DEV_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
          APPLE_DEV_PASSWORD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
          APPLE_DEV_APP_ID: ${{ secrets.PROD_MACOS_APPLE_DEV_APP_ID }}
        run: |
          ./scripts/ci-sign-macos.ps1 bin_${{ matrix.dimensions }}/addons/godot-rapier2d/bin/libphysics_server_rapier2d.ios.template_debug.dylib
          ./scripts/ci-sign-macos.ps1 bin_${{ matrix.dimensions }}/addons/godot-rapier2d/bin/libphysics_server_rapier2d.ios.template_release.dylib
        if: ${{ env.APPLE_DEV_ID }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: godot-rapier-${{ matrix.dimensions }}-${{ matrix.precision }}-${{ matrix.features.name }}
          path: |
            ${{ github.workspace }}/bin_${{ matrix.dimensions }}/**
            !${{ github.workspace }}/bin_${{ matrix.dimensions }}/project.godot
          if-no-files-found: error
          overwrite: true
