name: 🐧 Linux Builds
on:
  workflow_call:

jobs:
  linux:
    runs-on: ubuntu-20.04
    name: ${{ matrix.arch }} ${{ matrix.precision }} ${{ matrix.features }}
    strategy:
      fail-fast: false
      matrix:
        #arch: ["x86_64-unknown-linux-gnu", "i686-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]
        arch: ["x86_64-unknown-linux-gnu"]
        precision: [single]
        features: ["simd-stable,parallel", enhanced-determinism]

    steps:
      - uses: actions/checkout@v4
      - name: "Install dependencies"
        shell: sh
        run: |
          sudo apt-get update
          sudo apt-get install libunwind-dev
          sudo apt-get install build-essential
          sudo apt-get install pkg-config
          sudo apt-get install libssl-dev
          sudo apt-get install zlib1g-dev
      - name: Build ${{ matrix.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
          platform: linux
          precision: ${{ matrix.precision }}
          features: ${{ matrix.features }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: godot-rapier-2d-${{ matrix.precision }}-${{ matrix.features }}
          path: |
            ${{ github.workspace }}/bin/**
            !${{ github.workspace }}/bin/project.godot
    
