name: 🐧 Linux Builds
on:
  workflow_call:

jobs:
  linux:
    runs-on: ubuntu-20.04
    name: ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
    strategy:
      fail-fast: false
      matrix:
        # TODO , {arch: "x86_32", rust: "i686-unknown-linux-gnu"}, {arch: "arm64", rust: "aarch64-unknown-linux-gnu"}]
        # Right now it's giving this error (arm64):
        # cc1plus: error: bad value ('armv8-a') for '-march=' switch
        # Right now it's giving this error (x64_32):
        # /usr/include/c++/9/cstddef:49:10: fatal error: bits/c++config.h: No such file or directory 49 | #include <bits/c++config.h>
        arch: [{arch: "x86_64", rust: "x86_64-unknown-linux-gnu"}]
        precision: [single]
        features: [simd-stable, enhanced-determinism]
        rust_features: ["simd-stable,parallel", enhanced-determinism]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Fix 32bit and arm64 libs
        run: |
          sudo apt-get install gcc-multilib g++-multilib

      - name: Build ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch.arch }}
          rust_target: ${{ matrix.arch.rust }}
          platform: linux
          precision: ${{ matrix.precision }}
          features: ${{ matrix.rust_features }}

      - name: Upload ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/upload
        with:
          precision: ${{ matrix.precision }}
          features: ${{ matrix.features }}
    
