name: 🐧 Linux Builds
on:
  workflow_call:

jobs:
  linux:
    runs-on: ubuntu-20.04
    name: ${{ matrix.dimensions }} ${{ matrix.arch }} ${{ matrix.precision }} ${{ matrix.features }}
    strategy:
      fail-fast: false
      matrix:
        #arch: ["x86_64-unknown-linux-gnu", "i686-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]
        arch: ["x86_64-unknown-linux-gnu"]
        precision: [single]
        dimensions: [dim2, dim3]
        features: ["rapier2d/parallel,rapier2d/simd-stable", "rapier/enhanced-determinism"]

    steps:
      - uses: actions/checkout@v4
      - name: "Install dependencies"
        shell: sh
        run: |
          sudo apt-get update
          sudo apt-get install libunwind-dev
          sudo apt-get install build-essential
          sudo apt-get install pkg-config
          sudo apt-get install libssl-dev
          sudo apt-get install zlib1g-dev
      - name: Build ${{ matrix.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
          features: ${{ matrix.features }},${{ matrix.precision }}_${{ matrix.dimensions }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: godot-rapier-${{ matrix.dimensions }}-${{ matrix.precision }}-${{ matrix.features }}
          path: |
            ${{ github.workspace }}/bin_${{ matrix.dimensions }}/**
            !${{ github.workspace }}/bin_${{ matrix.dimensions }}/project.godot
          if-no-files-found: error
          overwrite: true
    
