name: 🍎 macOS Builds
on:
  workflow_call:

jobs:
  macos:
    runs-on: "macos-latest"
    name: ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
    strategy:
      fail-fast: false
      matrix:
        arch:  [{arch: "universal", rust: "x86_64-apple-darwin"}]
        precision: [single, double]
        features: [simd-stable, enhanced-determinism]
        rust_features: ["simd-stable,parallel", enhanced-determinism]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
    
      - name: Build {{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch.arch }}
          rust_target: ${{ matrix.arch.rust }}
          platform: macos
          precision: ${{ matrix.precision }}
          features: ${{ matrix.rust_features }}
      
      - name: Mac Sign
        uses: ughuuu/godot-cpp-template/.github/actions/sign@add-more-stuff/options-to-build
        with:
          FRAMEWORK_PATH: bin/addons/godot-rapier2d/bin/libphysics_server_rapier2d.macos.template_debug.framework
          SIGN_FLAGS: "--deep"
          APPLE_CERT_BASE64: ${{ secrets.APPLE_CERT_BASE64 }}
          APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
          APPLE_DEV_PASSWORD: ${{ secrets.APPLE_DEV_PASSWORD }}
          APPLE_DEV_ID: ${{ secrets.APPLE_DEV_ID }}
          APPLE_DEV_TEAM_ID: ${{ secrets.APPLE_DEV_TEAM_ID }}
          APPLE_DEV_APP_ID: ${{ secrets.APPLE_DEV_APP_ID }}
      - name: Mac Sign
        uses: ughuuu/godot-cpp-template/.github/actions/sign@add-more-stuff/options-to-build
        with:
          FRAMEWORK_PATH: bin/addons/godot-rapier2d/bin/libphysics_server_rapier2d.macos.template_release.framework
          SIGN_FLAGS: "--deep"
          APPLE_CERT_BASE64: ${{ secrets.APPLE_CERT_BASE64 }}
          APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
          APPLE_DEV_PASSWORD: ${{ secrets.APPLE_DEV_PASSWORD }}
          APPLE_DEV_ID: ${{ secrets.APPLE_DEV_ID }}
          APPLE_DEV_TEAM_ID: ${{ secrets.APPLE_DEV_TEAM_ID }}
          APPLE_DEV_APP_ID: ${{ secrets.APPLE_DEV_APP_ID }}
      - name: Upload {{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/upload
        with:
          precision: ${{ matrix.precision }}
          features: ${{ matrix.features }}
