name: 🍎 macOS Builds
on:
  workflow_call:

jobs:
  macos:
    runs-on: "macos-latest"
    name: ${{ matrix.dimensions }} ${{ matrix.precision }} ${{ matrix.features.name }} ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch:  ["x86_64-apple-darwin"]
        precision: [single]
        dimensions: [dim2, dim3]
        features: [{"feature":"rapier2d/parallel,rapier2d/simd-stable", "name": "normal"}, {"feature":"rapier/enhanced-determinism", "name": "enhanced-determinism"}]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
          features: ${{ matrix.features.feature }},${{ matrix.precision }}_${{ matrix.dimensions }}
      
      - name: Mac Sign
        uses: ughuuu/godot-cpp-template/.github/actions/sign@add-more-stuff/options-to-build
        with:
          FRAMEWORK_PATH: bin_${{ matrix.dimensions }}/addons/godot-rapier2d/bin/libphysics_server_rapier2d.macos.template_debug.framework
          SIGN_FLAGS: "--deep"
          APPLE_CERT_BASE64: ${{ secrets.APPLE_CERT_BASE64 }}
          APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
          APPLE_DEV_PASSWORD: ${{ secrets.APPLE_DEV_PASSWORD }}
          APPLE_DEV_ID: ${{ secrets.APPLE_DEV_ID }}
          APPLE_DEV_TEAM_ID: ${{ secrets.APPLE_DEV_TEAM_ID }}
          APPLE_DEV_APP_ID: ${{ secrets.APPLE_DEV_APP_ID }}
      - name: Mac Sign
        uses: ughuuu/godot-cpp-template/.github/actions/sign@add-more-stuff/options-to-build
        with:
          FRAMEWORK_PATH: bin_${{ matrix.dimensions }}/addons/godot-rapier2d/bin/libphysics_server_rapier2d.macos.template_release.framework
          SIGN_FLAGS: "--deep"
          APPLE_CERT_BASE64: ${{ secrets.APPLE_CERT_BASE64 }}
          APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
          APPLE_DEV_PASSWORD: ${{ secrets.APPLE_DEV_PASSWORD }}
          APPLE_DEV_ID: ${{ secrets.APPLE_DEV_ID }}
          APPLE_DEV_TEAM_ID: ${{ secrets.APPLE_DEV_TEAM_ID }}
          APPLE_DEV_APP_ID: ${{ secrets.APPLE_DEV_APP_ID }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: godot-rapier-${{ matrix.dimensions }}-${{ matrix.precision }}-${{ matrix.features.name }}
          path: |
            ${{ github.workspace }}/bin_${{ matrix.dimensions }}/**
            !${{ github.workspace }}/bin_${{ matrix.dimensions }}/project.godot
          if-no-files-found: error
          overwrite: true
