name: Release
on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      #- name: Download artifacts
      #  uses: actions/download-artifact@v3
      #  with:
      #    name: godot-rapier-2d-double-enhanced-determinism
      #    path: godot-rapier-2d-double-enhanced-determinism
      #- name: Download artifacts
      #  uses: actions/download-artifact@v3
      #  with:
      #    name: godot-rapier-2d-double-simd-stable
      #    path: godot-rapier-2d-double-simd-stable
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: godot-rapier-2d-single-enhanced-determinism
          path: godot-rapier-2d-single-enhanced-determinism
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: godot-rapier-2d-single-simd-stable
          path: godot-rapier-2d-single-simd-stable
      - name: Delete draft release(s)
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        shell: sh
        run: |
          #zip -r "godot-rapier-2d-double-enhanced-determinism.zip" godot-rapier-2d-double-enhanced-determinism
          #zip -r "godot-rapier-2d-double-simd-stable.zip" godot-rapier-2d-double-simd-stable
          zip -r "godot-rapier-2d-single-enhanced-determinism.zip" godot-rapier-2d-single-enhanced-determinism
          zip -r "godot-rapier-2d-single-simd-stable.zip" godot-rapier-2d-single-simd-stable
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Godot Rapier 2D
          #godot-rapier-2d-double-enhanced-determinism.zip
          #godot-rapier-2d-double-simd-stable.zip
          files: |
            godot-rapier-2d-single-enhanced-determinism.zip
            godot-rapier-2d-single-simd-stable.zip
          generate_release_notes: true
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
