name: 🔗 Builds
on: 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

#concurrency:
#  group: ${{ github.workflow }}
#  cancel-in-progress: true

jobs:
  static-checks:
    name: 📊 Static checks
    uses: ./.github/workflows/static_checks.yml

  android-build:
    name: 🤖 Android
    needs: static-checks
    uses: ./.github/workflows/android_builds.yml

  ios-build:
    name: 🍏 iOS
    needs: static-checks
    uses: ./.github/workflows/ios_builds.yml

  linux-build:
    name: 🐧 Linux
    needs: static-checks
    uses: ./.github/workflows/linux_builds.yml

  macos-build:
    name: 🍎 macOS
    needs: static-checks
    uses: ./.github/workflows/macos_builds.yml
    secrets: inherit

  windows-build:
    name: 🏁 Windows
    needs: static-checks
    uses: ./.github/workflows/windows_builds.yml

  web-build:
    name: 🌐 Web Builds
    needs: static-checks
    uses: ./.github/workflows/web_builds.yml

  release:
    name: Create Release
    permissions:
      contents: write
    needs: [android-build, ios-build, linux-build, macos-build, windows-build, web-build]
    uses: ./.github/workflows/release.yml
