name: 📊 Static Checks
on:
  workflow_call:

jobs:
  static-checks:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Format
        shell: sh
        run: cargo fmt --all -- --config-path ./rustfmt.toml
