name: 🧪 Run Tests
on:
  workflow_call:

jobs:
  run-tests-2d:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chickensoft-games/setup-godot@v1
        name: 🤖 Setup Godot
        with:
          version: 4.3.0
          use-dotnet: false
          include-templates: true
      - name: Run Tests for 2D Build
        shell: sh
        run: |
          cargo test --all-targets --features="build2d,test" --no-default-features
          ./scripts/build-dev-2d.sh
          godot --headless --path ./bin2d test.tscn --quit-after 1000 > output.log 2>&1
          if grep -q "ERROR:" output.log; then
            echo "Error found in output"
            exit 1
          else
            echo "No errors found"
          fi

  run-tests-3d:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests for 3D Build
        shell: sh
        run: |
          cargo test --all-targets --features="build3d,test" --no-default-features
