name: 🌐 Web Builds
on:
  workflow_call:

jobs:
  web:
    runs-on: ubuntu-20.04
    name: ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
    strategy:
      fail-fast: false
      matrix:
        arch: ["wasm32-unknown-emscripten"]
        precision: [single]
        features: ["", enhanced-determinism]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Emscripten latest
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: 3.1.39
          no-cache: true

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Rust Install Nightly
        run: |
          rustup toolchain install nightly
          rustup override set nightly
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Build ${{ matrix.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch.arch }}
          extra_flags: "-Z build-std=panic_abort,std"
          platform: web
          precision: ${{ matrix.precision }}
          features: ${{ matrix.features }}
          env_flags: "-C target-feature=+atomics,+bulk-memory"

      - name: Upload ${{ matrix.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/upload
        with:
          precision: ${{ matrix.precision }}
          features: ${{ matrix.features }}
    
