name: 🌐 Web Builds
on:
  workflow_call:

jobs:
  web:
    runs-on: ubuntu-20.04
    name: ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
    strategy:
      fail-fast: false
      matrix:
        arch: [{arch: "wasm32", rust: "wasm32-unknown-emscripten", rust_extra_flags: "-Z build-std=panic_abort,std"}]
        precision: [single, double]
        features: [simd-stable, enhanced-determinism]
        # Web doesnt support simd-stable
        rust_features: ["", enhanced-determinism]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Emscripten latest
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: 3.1.45
          no-cache: true

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Rust Install Nightly
        run: |
          rustup toolchain install nightly
          rustup override set nightly
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Build ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch.arch }}
          rust_target: ${{ matrix.arch.rust }}
          rust_extra_flags: ${{ matrix.arch.rust_extra_flags }}
          platform: web
          precision: ${{ matrix.precision }}
          features: ${{ matrix.rust_features }}
          rust_env_flags: "-C target-feature=+atomics,+bulk-memory"

      - name: Upload ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/upload
        with:
          precision: ${{ matrix.precision }}
          features: ${{ matrix.features }}
    
