name: 🌐 Web Builds
on:
  workflow_call:

jobs:
  web:
    runs-on: ubuntu-20.04
    name: ${{ matrix.dimensions.short }} ${{ matrix.precision }} ${{ matrix.features.name }} ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch: ["wasm32-unknown-emscripten"]
        precision: [single]
        dimensions: [{"feature": "dim2", "short": "2d"}, {"feature": "dim3", "short": "3d"}]
        features: [{"feature":"", "name": "normal"}, {"feature":"enhanced-determinism", "name": "enhanced-determinism"}]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Emscripten latest
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: 3.1.39
          no-cache: false

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Rust Install Nightly
        run: |
          rustup toolchain install nightly
          rustup override set nightly
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Build ${{ matrix.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
          extra_flags: "-Z build-std=panic_abort,std"
          precision: ${{ matrix.precision }}
          features: ${{ matrix.features.feature }},${{ matrix.precision }}-${{ matrix.dimensions.feature }},experimental-wasm
          env_flags: "-C target-feature=+atomics,+bulk-memory"
      - name: Copy to bin
        shell: sh
        run: |
          mv target/release/libgodot_rapier.wasm bin${{ matrix.dimensions.short }}/addons/godot-rapier${{ matrix.dimensions.short }}/bin/libgodot_rapier.wasm
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: godot-rapier-${{ matrix.dimensions.short }}-${{ matrix.precision }}-${{ matrix.features.name }}-${{ matrix.arch}}
          path: |
            bin${{ matrix.dimensions.short }}/**/*.wasm
          if-no-files-found: error
    
