name: 🏁 Windows Builds
on:
  workflow_call:

jobs:
  build-windows:
    runs-on: "windows-latest"
    name: ${{ matrix.dimensions.short }} ${{ matrix.precision }} ${{ matrix.features.name }} ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64-pc-windows-msvc", "i686-pc-windows-msvc"]
        precision: [single]
        dimensions: [{"feature": "dim2", "short": "2d"}, {"feature": "dim3", "short": "3d"}]
        features: [{"feature":"parallel,simd-stable", "name": "normal"}, {"feature":"enhanced-determinism", "name": "enhanced-determinism"}]

    steps:
      - uses: actions/checkout@v4
      - name: Build ${{ matrix.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
          features: ${{ matrix.features.feature }},${{ matrix.precision }}_${{ matrix.dimensions.feature }}
      - name: Copy to bin
        shell: sh
        run: |
          cp -rf target/release/libgodot_rapier.wasm bin${{ matrix.dimensions.short }}/addons/godot-rapier${{ matrix.dimensions.short }}/bin/libgodot_rapier.windows.dll
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: godot-rapier-${{ matrix.dimensions.short }}-${{ matrix.precision }}-${{ matrix.features.name }}
          path: |
            ${{ github.workspace }}/bin${{ matrix.dimensions.short }}//**
            !${{ github.workspace }}/bin${{ matrix.dimensions.short }}//project.godot
          if-no-files-found: error
          overwrite: true
